services:
  - type: web
    name: backend-service
    env: node
    rootDir: back_end
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
